# Aula 4 - Grafos 1

Na aula de hoje, vamos explorar os seguintes tópicos em Python:

- 1) Grafos

_________

## 1) Grafos / Graph

Um grafo é um par de conjuntos, `G = (V, E)`, sendo um deles o conjunto de **vértices** `V` e o outro um conunto de **arestas** `E`, onde cada aresta é um par de vértices.

Os vértices, muitas vezes também chamados de **nós**, são os itens de interesse do que se quer modelar, e as arestas são as conexoes ou relações entre estes itens.

Por exemplo, em uma aplicação logística, poderíamos modelar cada **local de entrega** como um vértice do grafo e as arestas indicariam se existe um **caminho conectando estes dois pontos diretamente**.

<img src="https://algoritmosempython.com.br/images/algoritmos-python/algoritmos-grafos/ModelagemGrafosExemplo.png" width=200>

As arestas podem ser direcionadas (mão única) ou não direcionadas (mão dupla).

<img src="https://www.ime.usp.br/~pf/algoritmos_para_grafos/aulas/figs/Sedgewick-Wayne/TinyNetworkOnly.png" width=200>


Além disso, as arestas podem ter um rótulo associado à elas, indicando por exemplo o custo de percorrer um caminho, ou a distância entre dois pontos de interesse.

<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/Prim_Algorithm_0.svg/250px-Prim_Algorithm_0.svg.png" width=200>

Quando existe uma aresta conectando um vértice `u` à um vértice `v` (`u-v`), dizemos que `v` é vizinho de `u`.

Em grafos direcionados, é comum usarmos a nomenclatura de árvores e dizer que `u` é pai de `v` caso exista uma aresta direcionada `u -> v`

_________


### 1.1) Como representar um grafo no computador?

Existem diferentes maneiras de se representar o conceito de grafo no computador, e cada uma pode ser mais ou menos indicada dependendo do problema que se quer resolver ou da forma como se deciciu modelá-lo.
Vamos falar das duas maneiras mais comuns de representação.





#### Matriz de adjacências

Uma das maneiras mais simples de representar um grafo é utilizando uma **matriz de adjacências**.

Vemos um exemplo de visualização dessa estrutura na figura abaixo.

Para criar um grafo como uma matriz de adjacências, definimos uma matriz `M` de dimensões `n x n`, sendo `n` a quantidade de vértices.

Inicializamos a matriz com zeros, e "marcamos" `M[u][v]` com um valor diferente de zero caso exista uma aresta conectando o vértice `u` ao vértice `v`.

<img src="https://s3-sa-east-1.amazonaws.com/lcpi/1f5e0fd3-572c-479a-8a53-74d8212c5e5c.jpg" width=500>

No exemplo da figura acima vemos um grafo **não direcionado** e por isso temos a matriz **diagonalmente simétrica** (`M[u][v] == M[v][u]`). 


> Ou seja, a aresta `u-v` é "de mão dupla".


Mas com essa estrutura também é possivel modelar grafos direcioinados, basta não impor a simetria.

Dica: a ponta da flecha é a linha (a ideia é que a flecha sai da linha e vai pra coluna)


<img src="https://algoritmosempython.com.br/images/algoritmos-python/algoritmos-grafos/GrafoMatrizAdjacencia.png" width=400>

Essa estrutura também permite representar arestas com custo, basta utilizar o valor do custo para marcar a aresta no lugar da constante 1 que utilizamos.

<img src="https://www.researchgate.net/profile/Paula-Gabrielly-Rodrigues/publication/326722760/figure/fig5/AS:654507780345864@1533058223380/Figura-4-7-Grafo-nao-ponderado-A-e-ponderado-B-com-suas-respectivas-matrizes-de.png" width=500>

#### Lista de adjacências

Embora a matriz de adjacências seja uma maneira simples e flexível para representação dos grafos, podemos ver que, principalmente para **grafos esparsos (grafos com poucas arestas)**, ela tende a gerar um desperdício de espaço (armazenando um monte de zeros para as conexões que não existem no grafo).

Uma alternativa que mitiga esse desperdício de espaço é a **lista de adjacêcias**.

Nessa representação, cada vértice está associado a uma lista com seus vizinhos.

Assim, não gastamos espaço representando a ausência de arestas.

<img src="https://s3-sa-east-1.amazonaws.com/lcpi/9775dad0-c900-42e9-87fa-41d78b73444c.jpg" width=500>

Mas e se o grafo tiver uma grande quantidade de arestas? Ainda estariamos economizando espaço?

#### Comparação das estruturas

Para um grafo `G=(V,E)` composto de vértices `V` e arestas `E`, listamos a complexidade das operações mais básicas.

|                            	| Matriz de Adj. 	| Lista de Adj.  	|
|----------------------------	|----------------	|----------------	|
| inserir aresta             	| O(1)           	| O(1)           	|
| remover aresta             	| O(1)           	| O(grau_max(G)) 	|
| verificar adj. de dois nós 	| O(1)           	| O(grau_max(G)) 	|
| listar vizinhos de um nó   	| O(len(V))         	| O(grau_max(G)) 	|
| espaço de armazenamento    	| O(len(V)^2 )      	| O(len(V) + len(E))  |

Obs: O **grau** de um vértice, é a **quantidade de arestas que incide sobre esse vértice.** O grau máximo de um grafo `G` é o maior grau dentre todos os vértices de `G`.

Será que faz sentido dizer que uma representação é melhor que a outra?
Em que situações seria melhor usar a matriz? E a lista?

_________

### 1.2) Implementação

Abaixo vemos um exemplo de implementação de grafo como **matriz de adjacências**.

In [4]:
# Matriz de Adjacências

class GrafoMA:
    
    def __init__(self, n):
        
        # lista de listas inicializada em zero, n x n
        self.adj = [[0]*n for _ in range(n)]
        

    def __repr__(self):
        
        return str('\n'.join([str(line) for line in self.adj]))
    
    
    def add_arrow(self, a, b, weight=1):
        
        self.adj[a][b] = weight
        

    def add_edge(self, a, b, weight=1, mao_dupla=True):
        
        self.add_arrow(a, b, weight)
        
        if mao_dupla:
            self.add_arrow(b, a, weight)
            
            
    def get_neighbors(self, n):
        
        return [i for i, v in enumerate(self.adj[n]) if v != 0]

In [ ]:
g1 = GrafoMA(4)

g1

In [ ]:
g1.add_edge(0, 1)

g1

In [ ]:
g1.add_edge(2, 3, mao_dupla = False)

g1

In [ ]:
g1.add_edge(0, 3, 10, mao_dupla = False)

g1

In [ ]:
g1.get_neighbors(0)

In [ ]:
g1.get_neighbors(3)

Podemos também implementar a lista de adjacências:

In [ ]:
class GrafoLA:
    
    def __init__(self, n):
        
        self.adj = [[] for _ in range(n)]
    
    
    def __repr__(self):
        
        return '\n'.join([str(line) for line in self.adj])
    
    
    def add_arrow(self, n1, n2):
        
        self.adj[n1].append(n2)
        
    
    def add_edge(self, n1, n2, mao_dupla=True):
        
        self.adj[n1].append(n2)
        
        if mao_dupla:
            
            self.adj[n2].append(n1)
            
        
    def get_neighbors(self, n):
        
        return self.adj[n]

In [1]:
g2 = GrafoLA(4)

g2

NameError: name 'GrafoLA' is not defined

In [ ]:
g2.add_edge(0, 1)

g2.add_edge(2, 3, mao_dupla = False)

g2.add_edge(0, 3, mao_dupla = False)

g2

In [ ]:
g2.get_neighbors(0)

In [ ]:
g2.get_neighbors(3)

Pergunta: como representar grafos ponderados com lista de adjacência?

In [6]:
# Matriz de Adjacências
class GraphAM:
    def __init__(self, n):
        self.adj = [[0]* n for _ in range(n)]

    def __repr__(self):
        return str('\n'.join([str(line) for line in self.adj]))

    def add_arrow(self, a, b, weight=1):
        self.adj[a][b] = weight

    def add_edge(self, a, b, weight=1):
        self.add_arrow(a, b, weight)
        self.add_arrow(b, a, weight)

    def remove_arrow(self, a, b):
        self.adj[a][b] = 0

    def remove_edge(self, a, b):
        self.remove_arrow(a, b)
        self.remove_arrow(b, a)

    def get_neighbors(self, a, get_weights=False):
        if get_weights:
            return [(i, v) for i, v in enumerate(self.adj[a]) if v]
        return [i for i, v in enumerate(self.adj[a]) if v]

    def __len__(self):
        return len(self.adj)
    def __len__(self):
        return len(self.adj)

**exercício 1 - na aula de segunda!!**
Enunciado   
5. Considere um determinado número de cidades (`N`) e uma determinada quantidade de rotas (`M`) que você sabe que existem entre aquelas cidades.     
Com base nisso, você deve criar um script em Python que recebe um número N de cidades e um número M de caminhos que existem entre elas.     
Em seguida, seu programa vai ler quais são esses M caminhos e a distância deles.   

In [28]:
gQ1 = GraphAM(7)
gQ1.add_edge(1, 3)
gQ1.add_edge(3, 4)
gQ1.add_edge(3, 2)
gQ1.add_edge(2, 5)
gQ1.add_edge(5, 5)
gQ1.add_edge(4, 5)
gQ1.add_edge(4, 6)
gQ1.add_edge(5, 6)

print(gQ1)

[0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 1, 0, 0, 0]
[0, 0, 0, 1, 0, 1, 0]
[0, 1, 1, 0, 1, 0, 0]
[0, 0, 0, 1, 0, 1, 1]
[0, 0, 1, 0, 1, 1, 1]
[0, 0, 0, 0, 1, 1, 0]


In [7]:
# exercício 1 - na aula de segunda!!
g = GraphAM(7)
g.add_edge(0, 1, weight=7)
g.add_edge(0, 3, weight=5)
g.add_edge(1, 2, weight=8)
g.add_edge(1, 3, weight=9)
g.add_edge(1, 4, weight=7)
g.add_edge(2, 4, weight=5)
g.add_edge(3, 4, weight=1)
g.add_edge(3, 5, weight=6)
g.add_edge(4, 5, weight=8)
g.add_edge(4, 6, weight=9)
g.add_edge(5, 6, weight=1)

print(g)

[0, 7, 0, 5, 0, 0, 0]
[7, 0, 8, 9, 7, 0, 0]
[0, 8, 0, 0, 5, 0, 0]
[5, 9, 0, 0, 1, 6, 0]
[0, 7, 5, 1, 0, 8, 9]
[0, 0, 0, 6, 8, 0, 1]
[0, 0, 0, 0, 9, 1, 0]


In [8]:
# exercício 2 - utilize o numpy para implementar a matriz de adjacência!
import numpy as np

In [25]:
# Matriz de Adjacências
class GraphAMNumpy:
    def __init__(self, n):
        s = (n,n)
        self.adj = np.zeros(s)

    def __repr__(self):
        return str(self.adj)

    def add_arrow(self, a, b, weight=1):
        self.adj[a][b] = weight

    def add_edge(self, a, b, weight=1):
        self.add_arrow(a, b, weight)
        self.add_arrow(b, a, weight)

    def remove_arrow(self, a, b):
        self.adj[a][b] = 0

    def remove_edge(self, a, b):
        self.remove_arrow(a, b)
        self.remove_arrow(b, a)

    def get_neighbors(self, a, get_weights=False):
        if get_weights:
            return [(i, v) for i, v in enumerate(self.adj[a]) if v]
        return [i for i, v in enumerate(self.adj[a]) if v]

    def __len__(self):
        return len(self.adj)
    def __len__(self):
        return len(self.adj)

In [26]:
g_np = GraphAMNumpy(7)
g_np.add_edge(0, 1, weight=7)
g_np.add_edge(0, 3, weight=5)
g_np.add_edge(1, 2, weight=8)
g_np.add_edge(1, 3, weight=9)
g_np.add_edge(1, 4, weight=7)
g_np.add_edge(2, 4, weight=5)
g_np.add_edge(3, 4, weight=1)
g_np.add_edge(3, 5, weight=6)
g_np.add_edge(4, 5, weight=8)
g_np.add_edge(4, 6, weight=9)
g_np.add_edge(5, 6, weight=1)

print(g_np)

[[0. 7. 0. 5. 0. 0. 0.]
 [7. 0. 8. 9. 7. 0. 0.]
 [0. 8. 0. 0. 5. 0. 0.]
 [5. 9. 0. 0. 1. 6. 0.]
 [0. 7. 5. 1. 0. 8. 9.]
 [0. 0. 0. 6. 8. 0. 1.]
 [0. 0. 0. 0. 9. 1. 0.]]


_________

In [21]:
g_np[3,2]

TypeError: 'GraphAMNumpy' object is not subscriptable

### 1.3) Percurso

Quando utilizamos um grafo para modelar um problema, muitas vezes temos o interesse de **percorrer** esse grafo (Graph Traversal ou Search).

Percorrer um grafo é passar por cada nó "visitando" o nó apenas uma vez.

Muitas vezes o interesse está não na visita em si, mas no **caminho percorrido para se chegar a esse nó**, ou na **ordem em que estes nós são visitados** (veremos mais abaixo como um destes algoritmos de percurso pode ser usado para encontrar o menor caminho entre dois nós, por exemplo).

E é por isso que os algoritmos de percurso precisam respeitar as arestas do grafo e não podem simplesmente percorrer a lista de vértices.


Veremos, abaixo, os principais algoritmos de percurso!

<img src="https://miro.medium.com/max/1280/0*miG6xdyYzdvrB67S.gif" width=450>

#### Busca em profundidade (DFS - Depth First Search)

Uma das maneiras de se percorrer um grafo é a busca em profundidade, que pode ser facilmente implementada de maneira recursiva.

Sempre que a DFS encontra **um vértice não visitado** ela segue por esse vértice.

Ela tem esse nome pois ao percorrer o grafo ela "verticaliza".

Ou seja, ao escolher um "ramo" do grafo, segue por esse ramo até que ele termine.

Abaixo temos um exemplo de como a busca em profundidade percorreria esse grafo partindo do nó 0.

<img src="https://s3-sa-east-1.amazonaws.com/lcpi/0084b080-e980-46d0-8694-55895333a3e7.jpg" width=600>

Veja que, para que a nossa função não fique visitando os nós incessantemente (devido a possivel existência de ciclos no grafo) precisamos marcar de alguma forma que um nó já foi visitado.

#### Busca em largura (BFS - Breadth First Search)

A busca em largura pode ser vista como uma maneira um pouco mais estruturada de se percorrer o grafo, e também um pouquinho mais complicaa de se implementar.

A BFS visita os nós do grafo em "camadas" partindo da origem, cada camada está uma aresta a mais de distância da origem em relação a camada anterior.
Ou seja, partindo de um nó origem `s` os nós diretamente conectados a `s` (seus vizinhos) são visitados primeiro antes dos nós conectados aos vizinhos de `s` (seus "vizinhos de segundo grau").

A figura abaixo mostra um exemplo gráfico desse comportamento em camadas.

<img src="https://s3-sa-east-1.amazonaws.com/lcpi/a67dd98f-8578-4bda-a710-903d7de9ceb6.jpg" width=600>

Note que a ordem de visitação imposta pela BFS é parcial.
Existem diferentes ordenações possíveis que qualificam como percurso BFS, o importante é respeitar as camadas.
Por exemplo, não importa se 1 foi visitado antes do 3 ou se o 3 foi visitado antes do 1 desde que ambos tenham sido visitados antes de 2, 4 e 5.


_________

### 1.4) Menor caminho

Uma das aplicações mais comuns em grafos é o cálculo do menor caminho entre vértices.

Aqui veremos o problema conhecido como **Single Source Shortest Path** posto da seguinte forma: 

Dado um grafo `G` e um **vértice origem** `s` encontre o **menor caminho** partindo de `s` até **cada vértice** `v` pertencente a `G`.
 
Vamos começar com o caso de grafos sem custo (ou custo constante = 1) nas arestas, ou seja, o menor caminho nesse caso é o **caminho com menos arestas**.

> Considere a busca em largura (BFS).

Já sabemos que um nó que está a uma aresta de distância da origem será visitado na primeira camada, um nó que está a duas arestas da origem será visitado na segunda, e assim por diante.

Ou seja, os nós já são visitados na ordem de menor caminho e a camada dá o custo desse caminho!!




#### Menor caminho para grafos com peso nas arestas

Grafos sem custo nas arestas são muito utilizados e nesses casos a BFS modificada será suficiente para encontrar o menor caminho.

Porém, muitas aplicações precisam levar em conta custos diferentes para cada aresta.

Por exemplo a **distância entre duas cidades** ou o **custo de pedágio** para se utilizar determinada rodovia.

A figura abaixo mostra um grafo com custos nas aretas.

Note que a BFS indicaria que o menor caminho de 0 a 1 seria simplesmente 0->1, mas podemos ver que 0->2->1, embora utilize mais arestas, tem um custo menor. E agora?

<img src="https://s3-sa-east-1.amazonaws.com/lcpi/bafb6b0b-7d19-47d8-8b93-293e84b7a7cd.jpg" width=800>

Existem diferentes algoritmos para encontrar o menor caminho entre todos os vértices e um vértice origem (*Single Source Shortest Path Problem*).



## Algoritmo de Dijkstra

Aqui vamos utilizar o algoritmo de Dijkstra por ser um dos mais famosos.

Este algoritmo calcula **a menor distância entre um nó e todos os outros nós no grafo**.

Considere o grafo a seguir:

<img src="https://www.codingame.com/servlet/fileservlet?id=14497257275137" width=300>

Vamos calcular o menor caminho entre o nó **C** e todos os outros nó do grafo!!

Durante o algoritmo, vamos marcar todos os nós **com a menor distância entre este nó e o nó C**.

A distância entre o nó C e ele mesmo é 0.

Inicialmente, a distância entre todos os nós é $\infty$. Vai ficar claro porque.

A cada iteração, vamos também focar em um único nó, o **nó atual**, que será marcado por um ponto vermelho.

<img src="https://www.codingame.com/servlet/fileservlet?id=14497265537633" width=300>

Nós vamos também criar listas para os menores caminhos! Isso vai permitir termos não somente o comprimento dos menores caminhos entre os nós e **C**, como também o caminho em si!

Inicialmente, temos:

```
Caminho entre C e A = []
Caminho entre C e B = []
Caminho entre C e C = C
Caminho entre C e D = []
Caminho entre C e E = []
```

As listas serão alteradas toda vez que atualizarmos as distâncias mínimas, de modo que as listas finais expressarão o menor caminho!

Vamos ver o passo a passo:

### Nó atual: C

<img src="https://www.codingame.com/servlet/fileservlet?id=14497279927597" width=300>

<img src="https://www.codingame.com/servlet/fileservlet?id=14497284902206" width=300>

<img src="https://www.codingame.com/servlet/fileservlet?id=14497297264677" width=300>

<img src="https://www.codingame.com/servlet/fileservlet?id=14497301316895" width=300>

```
Caminho entre C e A = [C, A]
Caminho entre C e B = [C, B]
Caminho entre C e C = [C]
Caminho entre C e D = [C, D]
Caminho entre C e E = []
```

### Nó atual: A

<img src="https://www.codingame.com/servlet/fileservlet?id=14497311165233" width=300>

<img src="https://www.codingame.com/servlet/fileservlet?id=14497327460640" width=300>

```
Caminho entre C e A = [C, A]
Caminho entre C e B = [C, A, B]
Caminho entre C e C = [C]
Caminho entre C e D = [C, D]
Caminho entre C e E = []
```

### Nó atual: D

<img src="https://www.codingame.com/servlet/fileservlet?id=14497330975308" width=300>

```
Caminho entre C e A = [C, A]
Caminho entre C e B = [C, A, B]
Caminho entre C e C = [C]
Caminho entre C e D = [C, D]
Caminho entre C e E = [C, D, E]
```

### Nó atual: B

<img src="https://www.codingame.com/servlet/fileservlet?id=14497346742885" width=300>

### Nó atual: E

<img src="https://www.codingame.com/servlet/fileservlet?id=14497350226741" width=300>

### FIM

<img src="https://www.codingame.com/servlet/fileservlet?id=14497361633811" width=300>

```
Caminho entre C e A = [C, A]
Caminho entre C e B = [C, A, B]
Caminho entre C e C = [C]
Caminho entre C e D = [C, D]
Caminho entre C e E = [C, A, D, E]
```

Esquematicamente, temos o algoritmo:


- 1: Marque o nó de origem com distância zero, e os demais nós com distância $\infty$

- 2: Atribua aos nós não visitados a menor entre as distâncias atuais entre o nó C

- 3: Para cada vizinho V do nó C: adicione a distância atual de C com o peso da aresta conectando C-V. Se for menor que a distância atual de N, mude a distância atual para este valor.

- 4: Marque o nó atual C como visitado.

- 5: Se ainda houver nós não visitados, volte para o passo 2.

_________

## Na aula que vem: [NetworkX!](https://networkx.org/)

Conheceremos algumas funcionalidades desta biblioteca para a análise de grafos/redes em Python!

<img src="https://networkx.org/_static/networkx_logo.svg">

In [ ]:
# !pip install networkx

___________