<h2>NumPy</h2>
## O que é o NumPy?
<p>O NumPy é uma poderosa biblioteca Python que é usada principalmente para realizar cálculos em Arrays Multidimensionais. O NumPy fornece um grande conjunto de funções e operações de biblioteca que ajudam os programadores a executar facilmente cálculos numéricos. Esses tipos de cálculos numéricos são amplamente utilizados em tarefas como:</p>

**Tarefas matemáticas:** NumPy é bastante útil para executar várias tarefas matemáticas como integração numérica, diferenciação, interpolação, extrapolação e muitas outras. O NumPy possui também funções incorporadas para álgebra linear e geração de números aleatórios. É uma biblioteca que pode ser usada em conjuto do SciPy e Matplotlib, substituindo o MATLAB quando se trata de tarefas matemáticas.

**Processamento de Imagem e Computação Gráfica:** Imagens no computador são representadas como Arrays Multidimensionais de números. NumPy torna-se a escolha mais natural para o mesmo. O NumPy, na verdade, fornece algumas excelentes funções de biblioteca para rápida manipulação de imagens. Alguns exemplos são o espelhamento de uma imagem, a rotação de uma imagem por um determinado ângulo etc.

**Modelos de Machine Learning:** Ao escrever algoritmos de Machine Learning, supõe-se que se realize vários cálculos numéricos em Array. Por exemplo, multiplicação de Arrays, transposição, adição, etc. O NumPy fornece uma excelente biblioteca para cálculos fáceis (em termos de escrita de código) e rápidos (em termos de velocidade). Os Arrays NumPy são usados para armazenar os dados de treinamento, bem como os parâmetros dos modelos de Machine Learning.

### Instalando
Existem diversas formas de instalar o numpy. <br>
A mais simples é instalar o pacote Anaconda (https://www.anaconda.com/distribution/)<br>
que já vem com o Python e diversas bibliotecas científicas e ciência de dados instaladas.

Outra forma, caso você já tenha o python instalado mas não o numpy, <br>
é o utilizar o gerenciador e pacotes pip, através do comando no seu terminal:

In [7]:
$ pip install numpy

SyntaxError: invalid syntax (<ipython-input-7-d4d1c8b5813b>, line 1)

### Explorando a API do NumPy
Importando numppy com um alias np<br>
np é uma abreviação amplamente utilizada na comunidade python para o numpy.

In [9]:
import numpy as np

### 1D arrays
Array unidimensional, também chamado de vetor ou até mesmo matriz de 1 dimensão:

In [10]:
 a = np.array([1, 2, 3])
 # array([1, 2, 3])
 print(a)

[1 2 3]


Checando o tipo da variável a:

In [11]:
print(type(a))

<class 'numpy.ndarray'>


o nd significa n-dimensional

Checando o tipo de dados do array
Diversos tipos de dados são possíveis em um array numpy, os mais comuns são os numéricos:

 - int32
 - int64
 - float32
 - float64

In [12]:
a.dtype

dtype('int32')

A consistência do dado é forte...<br>
Se trocarmos um elemento na posição 0 para o valor 10, dará certo:

In [13]:
a[0] = 10

In [14]:
a

array([10,  2,  3])

Se trocarmos para ponto flutuante, o numpy irá truncar a parte decimal, dado que o array que criamos é intei

In [15]:
a[0] = 1.2

In [16]:
a

array([1, 2, 3])

2D arrays
Matrizes podem ser consideradas um `array` de 2 dimensões.

> ------    
> ### Observação

> O NumPy possui também uma estrutura, `matrix`, mas não é recomendado utilizá-la pela própria documentação oficial e poderá ser removida no futuro.
------    

Para criar uma matriz, basta aninhar múltiplas listas dentro de uma lista, como o exemplo a seguir:

In [17]:
b = np.array([[9.0, 8.0, 7.0],
                  [6.0, 5.0, 4.0]])

In [18]:
b

array([[9., 8., 7.],
       [6., 5., 4.]])

Propriedades  
Dimensão e formato   
Dois conceitos importantes já mencionados acima é o de dimensão e formato.   



Para descobrir essas informações, basta acessar os atributos [ndim] e [shape]

In [19]:
a.ndim

1

In [20]:
a.shape

(3,)

In [21]:
b.ndim

2

In [22]:
b.shape

(2, 3)

Tipo de dado e tamanho   
Na sessão `Checando o tipo de dados do array` já foi dito dos tipos de dados, mas agora falaremos da diferença de tamanhos que isso ocupa na memória.   
 
Então, temos as variáveis [a] e [b] criadas anteriormente com os seguintes tipos:

In [23]:
a.dtype

dtype('int32')

In [24]:
b.dtype

dtype('float64')

Por padrão, se o python instalado é 64 bits, ele irá criar tipos int ou float de 64 bits. Caso seu python fosse 32 bits, seria int32 e float32.

Vamos criar uma outra array, a16, com o tipo inteiro de 16 bits.

In [25]:
a16 = np.array([1, 2, 3], dtype=np.int16)
a16

array([1, 2, 3], dtype=int16)

Note que por ser um tipo diferente do padrão, ele ressalta ao imprimir.  
 
Para descobrir quanto cada elemento individualmente ocupa na memória, podemos acessar o atributo `itemsize`:  

In [26]:
a.itemsize

4

Ele retorna 8 e não 64! Isso é porque ele já converteu os bits para bytes. Bytes é o conjunto de 8 bits.

Logo:  $\huge \frac{32}{ 4 } = 4 $


In [27]:
a.size * a.itemsize

12

In [28]:
a.nbytes

12

> -----   
> Observação   
> 
> 
> Geralmente não é necessário em reduzir o número de bits a não ser que você tenha certeza que um tamanho reduzido vai atender sua necessidade e você quer ser extremamente eficiente.   
> 
> ------

Acessando e modificando elementos (Indexing & Slicing)   
Dada a matriz a abaixo:

In [56]:
a = np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


Podemos acessar um elemento específico de forma similar a lista, utilzando a sintaxe de colchetes, com a diferença de que podemos separar cada posição com vírgulas.    
  
Para uma array 2D, temos então a sintaxe:  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; $\large [linha, coluna ]$ 

In [33]:
a[0, 5]

6

Podemos (menos comum) fazer dessa forma também:

In [34]:
a[1][5]

13

Usar números negativsos funciona de trás pra frente a indexação:

In [35]:
a[1, -2]

13

Pegar uma linha específica, podemos utilizar a sintaxe de : que pode ser lida como "todos" daquela dimensão (colunas).    

Podemos ler então como: linha zero, todas as colunas   

In [36]:
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

Também podemos fazer assim simplesmente:

In [37]:
a[0]

array([1, 2, 3, 4, 5, 6, 7])

Porém, para coluna específica não tem jeito, precisamos usar :.

Leia-se: todas as linhas, coluna 2

In [38]:
a[:, 2]

array([ 3, 10])

In [ ]:
O operador : também conhecido como slicing, aceita o parâmetro:

 - start
 - end
 - step

No formato

[startindex:endindex:stepsize]

O stepsize basicamente é quantos elementos deve ser pular. Podemos pegar do elemento 1 ao 6 pulando de 2 em 2 por exemplo da linha 0.

In [39]:
a[0, 1:6:2]

array([2, 4, 6])

Funciona com negativo também:

In [40]:
a[0, 1:-1:2]

array([2, 4, 6])

Para mudar um elemento específico, basta usar o operador =:

In [41]:
a[1,5] = 20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


Mudando uma coluna inteira para ser 5:

In [42]:
a[:, 2] = 5
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


Isso mostra uma característica fundamental do array do NumPy:


> Ao alterar o pedaço da matriz recortada, você altera a matriz original

Slicing em listas geram cópias!

In [54]:
a = [1, 2, 3]
b = a[1:]
b


[2, 3]

In [55]:
b = [10, 11]
print(a)
print(b)

[1, 2, 3]
[10, 11]


Acessando o formato de um slicing:

In [58]:
a[:, 2].shape

(2,)

In [59]:
a[:, 2] = [5, 10]

In [60]:
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


Exemplo 3D

In [61]:
b = np.array([[[1, 2], [3,4]], [[5, 6], [7, 8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


Checando a dimensão:

In [62]:
b.ndim

3

Retirando o elemento 4:

In [63]:
b[0, 1, 1]

4

Pegando todos todos os elementos da posição 1 da dimensão 2:

In [64]:
b[:, 1, :]

array([[3, 4],
       [7, 8]])

Substituindo:

In [65]:
b[:, 1, :] = [[9, 9], [8, 8]]

Inicializando arrays usando métodos internos
O NumPy já possui diversos métodos built-in para gerar arrays dos mais diversos tipos

array apenas com zeros

In [66]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

É possível gerar um array de qualquer formato, basta apenasr passar o formato como uma sequência (lista, tupla geralmente) como argumento

In [67]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [68]:
np.zeros((2, 2, 3))

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

array apenas com uns

In [69]:
np.ones((4, 2, 2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

Um coisa muito comum é usar o np.ones para criar uma matriz de qualquer número fazendo a operação, exemplo:

In [70]:
np.ones((2, 2)) * 10

array([[10., 10.],
       [10., 10.]])

Mas o numpy já tem uma opção mais elegante, o full:

In [71]:
np.full((2, 2), 99)

array([[99, 99],
       [99, 99]])

Qualquer outro número copiando o formato de uma matriz existente

In [72]:
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

Números decimais aleatórios
O numpy tem um sub-módulo chamado `random`, que pode ser acessando via `np.random`.

Nele, tem um conjunto de funções para números aleatórios.

In [73]:
np.random.random_sample((4, 2))

array([[0.4982785 , 0.27544588],
       [0.90764279, 0.93080901],
       [0.13531892, 0.88303231],
       [0.86271855, 0.85410013]])

Função igual a de cima, mas padrão do MATLAB (observe que não é uma tupla/lista o formato):

In [74]:
np.random.rand(4, 2)

array([[0.88500112, 0.79080079],
       [0.05331885, 0.50583972],
       [0.62729845, 0.94125212],
       [0.7540487 , 0.28667321]])

Números inteiros:

In [76]:
np.random.randint(7, size=(3, 3))

array([[1, 1, 4],
       [2, 6, 3],
       [5, 0, 6]])

Os argumentos principais são `low`, `high` e `size`, exemplo: criando uma matriz de 0 a 99 de 100 elementos:

In [77]:
np.random.randint(0, high=100, size=100)

array([49, 61,  3, 62, 50, 38, 83, 97, 15, 65, 16, 63, 79, 51, 79, 32, 71,
       38, 36, 78, 25, 91, 95, 60, 41, 84,  7, 91, 62, 35, 54, 81, 92, 25,
       20, 44, 56, 36, 27, 30, 56, 18, 23, 36, 93, 40, 69, 19, 15,  8,  7,
       62, 14, 25,  5, 80, 54, 16, 12, 51, 91, 49, 93, 36, 60, 63, 51, 68,
       48, 47, 77, 77, 91, 28, 63,  9, 97, 94, 22, 16,  9,  7,  3, 42, 73,
       26, 38, 34, 41, 37, 84, 34, 60,  2, 99, 20, 54,  5, 64, 68])

Para incluir o 100, basta trocar o high por 101

Matriz identidade   
Diagonal inteira com 1. É sempre uma matriz quadrada.

In [78]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

repeat  
Método para repetir uma determinada array na direção do eixo escolhido.  
 
Esse é a primeira função, de várias, que possui o parâmetro axis. 
   
Diversas vezes o numpy permite fazer uma operação, nesse caso, repeat, no qual é opcional ou necessário dizer qual o eixo da operação.  
  
Para um vetor de 1D, temos apenas 1 eixo, mas para matrizes, tempos dois:  
  
O eixo 0 é linha, o eixo 1 é coluna  
  
>>> arr = np.array(\[1, 2, 3\])  

In [81]:
arr = np.array([1, 2, 3])
r1 = np.repeat(arr, 3)

In [82]:
print(r1)

[1 1 1 2 2 2 3 3 3]


Com axis = 0

In [83]:
arr = np.array([[1, 2, 3]])
r1 = np.repeat(arr, 3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


Com axis = 1

In [84]:
arr = np.array([[1, 2, 3]])
r1 = np.repeat(arr, 3, axis=1)
print(r1)

[[1 1 1 2 2 2 3 3 3]]


arange  
Função que retorna elementos igualmente espaçados num step (por padrão, 1) dentro de um certo intervalo.

In [85]:
 np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Step diferente de 1:

In [86]:
np.arange(0, 11, 0.1)

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,
        1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,
        2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,  3.2,
        3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,  4.3,
        4.4,  4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,  5.4,
        5.5,  5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,  6.5,
        6.6,  6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,
        7.7,  7.8,  7.9,  8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,
        8.8,  8.9,  9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,
        9.9, 10. , 10.1, 10.2, 10.3, 10.4, 10.5, 10.6, 10.7, 10.8, 10.9])

linspace   
Parecido com o arange, mas você diz quantos pontos você quer e o intervalo e ele define o espaçamento linear

In [88]:
np.linspace(0, 11, num=10)

array([ 0.        ,  1.22222222,  2.44444444,  3.66666667,  4.88888889,
        6.11111111,  7.33333333,  8.55555556,  9.77777778, 11.        ])

Tenha cuidado ao copiar arrays!  
Jeito errado  

In [89]:
a = np.array([1, 2, 3])
b = a
b

array([1, 2, 3])

In [90]:
b[0] = 100
print(b)
print(a)

[100   2   3]
[100   2   3]


> a também foi modificado!  

Jeito certo (seguro)  

In [91]:
a = np.array([1, 2, 3])
b = a.copy()
b[0] = 100
print(b)
print(a)

[100   2   3]
[1 2 3]


Matemática  
O numpy te fornece um conjunto de funções matemáticas:

In [93]:
a = np.array([1, 2, 3, 4])
print(a)

[1 2 3 4]


Operação com escalares    
Soma:

In [95]:
a + 2

array([3, 4, 5, 6])

Subtração:

In [96]:
a - 2

array([-1,  0,  1,  2])

Multiplicação:

In [97]:
a * 2

array([2, 4, 6, 8])

Divisão:

In [98]:
 a / 2

array([0.5, 1. , 1.5, 2. ])

Incrementar:

In [99]:
a += 2
a

array([3, 4, 5, 6])

Potência:

In [100]:
a ** 2

array([ 9, 16, 25, 36], dtype=int32)

Operação entre arrays   
Tudo que você consegue fazer com escalar, você consegue fazer com arrays elemento-a-elemnto, por exemplo, para soma:

In [101]:
a = np.array([1, 2, 3, 4])
b = np.array([1, 0, 1, 0])
a + b

array([2, 2, 4, 4])

Funções matemáticas  
Função seno

In [102]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

Funçõa cosseno:

In [103]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [ ]:
Álgebra Linear  
Da definição do Wikipédia:  

Álgebra linear é um ramo da matemática que surgiu do estudo detalhado de sistemas de equações lineares,   
sejam elas algébricas ou diferenciais.   
 A álgebra linear utiliza alguns conceitos e estruturas fundamentais da matemática como vetores,      
 espaços vetoriais, transformações lineares, sistemas de equações lineares e matrizes.   
   
O numpy nos permite executar diversas diversas operações de álgebra linear, mostradas a seguir:  

In [108]:
a = np.ones((2, 3))
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [110]:
b = np.full((3, 2), 2)
b


array([[2, 2],
       [2, 2],
       [2, 2]])

Transposição
A operação de transposição

$
\begin{bmatrix}
    x_{11} & x_{12} & x_{13} & \dots  & x_{1n} \\
    x_{21} & x_{22} & x_{23} & \dots  & x_{2n} \\
    \vdots & \vdots & \vdots & \ddots & \vdots \\
    x_{d1} & x_{d2} & x_{d3} & \dots  & x_{dn}
\end{bmatrix} 
 $=
 $
 \begin{bmatrix}
    x_{11} & x_{21} & x_{31} & \dots  & x_{d1} \\
    x_{12} & x_{22} & x_{23} & \dots  & x_{d2} \\
    \vdots & \vdots & \vdots & \ddots & \vdots \\
    x_{1n} & x_{2n} & x_{3n} & \dots  & x_{dn}
\end{bmatrix} 
 $


Pode ser feita da seguinte forma:

In [111]:
np.transpose(a)

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

Ou acessando o atributo `T`:

In [112]:
a.T

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

Multiplicação de matrizes
A tradicional multiplicação de matrizes, como mostra a imagem abaixo:<br>
<img width="25%" src="../../../MatrixMul.png">


Pode ser feita no numpy simplesmente chamando matmul

In [113]:
np.matmul(a, b)

array([[6., 6.],
       [6., 6.]])

Operador @ executa a função anterior:

In [114]:
a @ b

array([[6., 6.],
       [6., 6.]])

Encontrar o determinante

In [118]:
c = np.identity(3)
print(c)
np.linalg.det(c)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


1.0

Outras funcções de Álgebra Linear: https://docs.scipy.org/doc/numpy/reference/routines.linalg.html

 - Trace
 - Decomposição de vetores
 - Autovalor/autovetor
 - Norma da Matriz
 - Inversa
 - Etc...   
Estatística   
O numpy vem com várias funções básicas de estatística, como mínimo, máximo, média, mediana, etc.

In [120]:
stats = np.array([[1, 2, 3], [4, 5, 6]])

In [121]:
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [122]:
 np.min(stats)

1

In [123]:
np.max(stats)

6

In [124]:
np.min(stats, axis=1) 

array([1, 4])

Máximo por coluna:

In [125]:
np.max(stats, axis=0)

array([4, 5, 6])

Soma por coluna:

In [126]:
np.sum(stats, axis=0)

array([5, 7, 9])

Média:

In [127]:
np.average(stats)

3.5

Reorganizar Array  
Muitas vezes você quer mudar o formato de array, por exemplo, de 4 elementos pra uma matriz 2x2, ou situações similares.  
  
Para isso, você pode utilizar a função reshape.  
  
Reshape  

In [129]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before.shape)

(2, 4)


In [131]:
after = before.reshape((8, 1)) # tem que possuir a mesma quantidade!
after

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [132]:
before.reshape(2, 2, 2)

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

Anexar verticalmente os vetores

In [133]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

In [134]:
np.vstack([v1, v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [135]:
np.vstack([v1, v2, v2, v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

Apendar horizontalmente os vetores  
De forma similar ao anterior:  

In [137]:
h1 = np.ones((2, 4))
h2 = np.zeros((2, 2))
np.hstack((h1, h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

Funcionalidades extras  
Carregar dados de um arquivo  
Vamos supor que temos um arquivo data.txt com o seguinte conteúdo:  

In [ ]:
1,13,21,11,196,75,4,3,34,6,7,8,0,1,2,3,4,5
3,42,12,33,766,75,4,55,6,4,3,4,5,6,7,0,11,12
1,22,33,11,999,11,2,1,78,0,1,2,9,8,7,1,76,88

In [139]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata

array([[  1.,  13.,  21.,  11., 196.,  75.,   4.,   3.,  34.,   6.,   7.,
          8.,   0.,   1.,   2.,   3.,   4.,   5.],
       [  3.,  42.,  12.,  33., 766.,  75.,   4.,  55.,   6.,   4.,   3.,
          4.,   5.,   6.,   7.,   0.,  11.,  12.],
       [  1.,  22.,  33.,  11., 999.,  11.,   2.,   1.,  78.,   0.,   1.,
          2.,   9.,   8.,   7.,   1.,  76.,  88.]])

Podemos gerar uma matriz a partir desse arquivo da seguinte forma:

O primeiro argumento é o nome do arquivo.  

Importante ressaltar o segundo key argumento, delimiter, no qual você especifica o que separa cada número  
 individualmente no arquivo. Nesse caso, vírgula, mas podería ser ; por exemplo, espaços, ou tabs.  

Podemos notar também que o numpy converteu para float nossos números, apesar de todos serem inteiros.   
Ele faz isso como uma medida preventiva dado que ele não sabe ao ler o arquivo qual tipo de dado que é.  

Podemos converter manualmente para inteiro usando a função astype:  

In [140]:
filedata.astype('int32')

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]])

Podemos também salvar uma matriz de uma forma mais otimizada não textual (binária) para uso futuro.  
  
Isso gera um arquivo binário que inclusive salva o tipo de dado, nesse caso, int32.  
  
Quando lido, vai converter corretamnete o tipo daquele dado.  

In [142]:
np.save('data', filedata.astype('int32'))

Igual ao método de cima, porém comprime os dados (economiza espaço em disco, porém é um pouco mais lento pra ler).

In [143]:
np.savez_compressed('dataz', filedata)

Para ler os dados que acabamos de salvar, basta usar o np.load:

In [144]:
np.load('data.npy')

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]])

### Máscara Boleana e Seleção Avançada
Conceito super importante no numpy e no pandas é o de máscara booleana.

Ao aplicar qualquer operador booleano

  - \>
  - <
  - <=
  - \>=
  - ==
  - in  

o numpy retorna um array de `True` e `False` no qual ele aplicou elemento a elemento aquele operador.  
   
Imagine para a matriz abaixo:  

In [146]:
mat = np.array([1, 10, 20, 30]).reshape(2, 2)
arr

array([[1, 2, 3]])

Eu quero saber todos os elementos maiores que 10, eu posso aplicar:

In [147]:
mat > 10

array([[False, False],
       [ True,  True]])

Me é retornado uma matriz de formato (2, 2)  
assim como com True na posição dos elementos que são maiores que 10.  
  
Podemos então fazer essa operação dentro dos colchetes de seleção:

In [148]:
mat[mat > 10]

array([20, 30])

E será retornado um array com os elementos 20 e 30 como esperado.  
  
Podemos fazer operações linha a linha ou coluna a coluna através de métodos auxiliares como any ou all:  
  
any: se qualquer elemento da linha for True, retorna True  
all: todos os elementos tem que ser True para retornar True  
Exemplos:  
  
Por coluna:  

In [149]:
np.any(mat > 10, axis=0)

array([ True,  True])

Por linha:

In [150]:
np.any(mat > 10, axis=1)

array([False,  True])

Operador AND
Similar ao and do python, podemos usar múltiplas condições para filtrar dados da nossa matriz com o operador &.

In [151]:
filt = (mat > 10) & (mat <= 20)
mat[filt]


array([20])

> Observação: note que os colchetes além de melhorarem a legibilidade,  
> são necessárias devido a ordem de precedência dos operadores python.   
> Se não colocarmos os colchetes, dará um erro.

Operador OR  
Similar ao or, só que devemos utilizar |:

In [152]:
filt = (mat == 1) | (mat >= 20)
mat[filt]

array([ 1, 20, 30])

Operador NOT  
Similar ao not, mas devemos utilizar um til ~

In [154]:
filt = (mat == 1) | (mat >= 20)
mat[~filt]

array([10])

In [ ]:
array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])

Seleção passando listas  
Podemos selecionar elementos específicos de um array passando uma lista de posições:  

In [155]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
a[[1, 2, 8]]

array([2, 3, 9])

Referências  
https://github.com/numpy/numpy  
https://docs.scipy.org/doc/numpy/reference/  
https://docs.scipy.org/doc/numpy/reference/routines.math.html  
https://docs.scipy.org/doc/numpy/reference/routines.linalg.html  