# Questão #1  
Vale  1  
Enunciado  
Dado o array:  
  
arr = np.arange(50)  
Selecione a alternativa INCORRETA na utilização de filtros e máscaras neste Numpy array.    
- [ ] arr_atualizado = arr\[arr % 2\]  
- [ ] arr_atualizado = arr\[arr>5\]  
- [ ] arr_atualizado = arr\[arr <=10 \]
- [x] arr_atualizado = arr\[(arr != 1) or (arr != 3)\] # x

In [2]:
import numpy as np

In [3]:
arr = np.arange(50)
arr_atualizado = arr[arr % 2]
print(arr_atualizado)
arr_atualizado = arr[arr>5]
print(arr_atualizado)
arr_atualizado = arr[arr <=10 ]
print(arr_atualizado)
arr_atualizado = arr[(arr != 1) | (arr != 3)] # x
print(arr_atualizado)

[0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0
 1 0 1 0 1 0 1 0 1 0 1 0 1]
[ 6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29
 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]


# Questão #2  
Vale 5  
Enunciado  
Agora, vamos explorar os arrays aleatórios e máscaras. Faça o que se pede:  
  
a) Crie um array aleatório de 15 itens entre 0 e 100;  
  
b) Qual o maior número do array?  
  
c) Qual a sua posição?  
  
d) Verifique quais números do array são maior que 10;  
  
e) Salve em uma nova lista apenas os itens entre 10 e 30.  

In [15]:
arr = np.random.uniform(low=0, high=100, size=15)
print(f"a) {arr}")
print(f"b) {arr.max()}")
print(f"c) {arr.argmax()}")
maiorDex = arr[arr > 10]
print(f"d) {maiorDex}")
ardeDezATrinta = arr[(arr >= 10) & (arr <= 30)]
print(f"e) {ardeDezATrinta}")

a) [19.46463333 82.74394273 22.68799978 27.18956926  6.97970728 40.85305454
 79.90779695 62.85233427  0.72649451  8.06141543  2.35385721  8.5078642
 20.69958155 48.4539055  67.60960113]
b) 82.74394272904331
c) 1
d) [19.46463333 82.74394273 22.68799978 27.18956926 40.85305454 79.90779695
 62.85233427 20.69958155 48.4539055  67.60960113]
e) [19.46463333 22.68799978 27.18956926 20.69958155]


#  Questão #3
Vale 10  
Enunciado  
Nosso próximo foco serão as matrizes. Faça o que se pede:  
  
a) Gere uma matriz (3,2) com números linearmente espaçados entre 0 e 100 e intervalos de 20, usando o `np.linspace()`;  
  
b) Gere uma matriz aleatória (5,2) com números entre 0 e 100;  
  
c) Crie um array com as dimensões apropriadas que, quando multiplicado pela matriz do item a), 
    devolva essa mesma matriz. Use o método `np.matmul()`.  

In [19]:
arr = np.linspace(0,100,num=6,retstep=False).reshape(3,2)
print(arr)

[[  0.  20.]
 [ 40.  60.]
 [ 80. 100.]]


In [18]:
# sampl = np.random.uniform(low=0, high=100, size=(10,)).reshape(5,2)
sampl = np.random.randint(0, high=100, size=(5,2))
print(sampl)

[[32 36]
 [44 17]
 [79 60]
 [ 6 47]
 [78 36]]


In [23]:
arr2 = np.linspace(0,100,num=6,retstep=False).reshape(2,3)
arr2 = np.ones((2,3))
np.matmul(arr,arr2)


array([[ 20.,  20.,  20.],
       [100., 100., 100.],
       [180., 180., 180.]])